changeLogFile=changelog/changelog-v0.0.1.sql

liquibase.command.username: postgres
liquibase.command.password: math-face-pass

liquibase.command.referenceUrl: jdbc:postgresql://psql:5432/math_face
liquibase.command.referenceUsername: postgres
liquibase.command.referencePassword: math-face-pass
