ktor:
  development: true
  deployment:
    port: 8080
  application:
    modules:
      - io.github.geniyyc.mathface.app.ktor.ApplicationKt.module
  logger: logback

mathface:
  repository:
    test: "inmemory"
    prod: "$MATHFACE_REPOSITORY_PROD:inmemory"

    psql:
      schema: public
      database: "$MKPLADS_DB:math_face"
      host: "$MKPLADS_HOST:localhost"
      port: "$MKPLADS_PORT:5432"
      user: "$MKPLADS_USER:postgres"
      password: "$MKPLADS_PASS:math-face-pass"
